-
  name: Running APT to update the system.
  hosts:  debian
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
      become: yes
    - name: upgrade all packages
      dnf:
        name: "*"
        state: latest
      become: yes